### ISSUE TITLE
azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar seems to be containing an older version of reactor

### ISSUE THREAD

**Issue by stevenylai** [Azure/azure-schema-registry-for-kafka#32]
When I use azure-schemaregistry-kafka-avro-1.0.0-beta.7 in conjunction with spring 2.7.4 and `azure-cosmos` from `azure-sdk-bom-1.2.1`. I got the following:
```
2022-10-07 14:04:01.263 ERROR 13792 --- [smos-parallel-1] reactor.core.scheduler.Schedulers        : Scheduler worker in group main failed with an uncaught exception

java.lang.NoSuchMethodError: 'reactor.util.context.ContextView reactor.core.publisher.MonoSink.contextView()'
        at reactor.netty.http.client.HttpClientConnect$HttpObserver.<init>(HttpClientConnect.java:330) ~[reactor-netty-http-1.0.23.jar!/:1.0.23]
        at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:260) ~[reactor-netty-http-1.0.23.jar!/:1.0.23]
        at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:273) ~[reactor-netty-http-1.0.23.jar!/:1.0.23]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:236) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4400) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.FluxFromMonoOperator.subscribe(FluxFromMonoOperator.java:76) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

2022-10-07 14:06:00.946 ERROR 13792 --- [           main] c.a.c.i.RxDocumentClientImpl             : unexpected failure in initializing client.

java.lang.IllegalStateException: Timeout on blocking read for 120000000000 NANOSECONDS
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at reactor.core.publisher.Mono.block(Mono.java:1731) ~[azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/:1.0.14]
        at com.azure.cosmos.implementation.GlobalEndpointManager.init(GlobalEndpointManager.java:77) ~[azure-cosmos-4.28.1.jar!/:4.28.1]
        at com.azure.cosmos.implementation.RxDocumentClientImpl.init(RxDocumentClientImpl.java:437) ~[azure-cosmos-4.28.1.jar!/:4.28.1]
        at com.azure.cosmos.implementation.AsyncDocumentClient$Builder.build(AsyncDocumentClient.java:245) ~[azure-cosmos-4.28.1.jar!/:4.28.1]
        at com.azure.cosmos.CosmosAsyncClient.<init>(CosmosAsyncClient.java:127) ~[azure-cosmos-4.28.1.jar!/:4.28.1]
        at com.azure.cosmos.CosmosClientBuilder.buildAsyncClient(CosmosClientBuilder.java:773) ~[azure-cosmos-4.28.1.jar!/:4.28.1]
        at com.ubs.si.core.methodology_coordinator.infra.CosmosConfigAsync.init(CosmosConfigAsync.java:70) ~[classes!/:${release.version}]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.23.jar!/:5.3.23]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.3.23.jar!/:5.3.23]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.3.23.jar!/:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440) ~[spring-beans-5.3.23.jar!/:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.3.23.jar!/:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.23.jar!/:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar!/:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar!/:5.3.23]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar!/:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar!/:5.3.23]
```

Further more, in container it reports:
```
***************************
APPLICATION FAILED TO START
***************************
 
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    reactor.netty.http.client.HttpClientConnect$HttpObserver.<init>(HttpClientConnect.java:330)
 

The following method did not exist:

    'reactor.util.context.ContextView reactor.core.publisher.MonoSink.contextView()'

The calling method's class, reactor.netty.http.client.HttpClientConnect$HttpObserver, is available from the following locations:

    jar:file:/opt/app/bin/app.jar!/BOOT-INF/lib/reactor-netty-http-1.0.23.jar!/reactor/netty/http/client/HttpClientConnect$HttpObserver.class
    jar:file:/opt/app/bin/app.jar!/BOOT-INF/lib/azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/reactor/netty/http/client/HttpClientConnect$HttpObserver.class
 

The calling method's class was loaded from the following location:

    jar:file:/opt/app/bin/app.jar!/BOOT-INF/lib/reactor-netty-http-1.0.23.jar!/

The called method's class, reactor.core.publisher.MonoSink, is available from the following locations:

    jar:file:/opt/app/bin/app.jar!/BOOT-INF/lib/azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/reactor/core/publisher/MonoSink.class
    jar:file:/opt/app/bin/app.jar!/BOOT-INF/lib/reactor-core-3.4.23.jar!/reactor/core/publisher/MonoSink.class

The called method's class hierarchy was loaded from the following locations:

    reactor.core.publisher.MonoSink: jar:file:/opt/app/bin/app.jar!/BOOT-INF/lib/azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar!/

Action:

Correct the classpath of your application so that it contains compatible versions of the classes reactor.netty.http.client.HttpClientConnect$HttpObserver and reactor.core.publisher.MonoSink
```

So it seems that azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar is including a version of MonoSink.class which does not have the required method?

**Comment by stevenylai** [comment]
Upon a closer inspection, looks like the not found method was [introduced](https://github.com/reactor/reactor-core/blob/v3.4.18/reactor-core/src/main/java/reactor/core/publisher/MonoSink.java) since `reactor-core:3.4.18`.  The dependency on Azure side is:

`azure-schemaregistry-kafka-avro:1.0.0-beta.7` -> `azure-core-http-netty:1.11.9` -> `reactor-netty-http:1.0.15` -> `reactor-core:3.4.14`

While spring has:

`spring-boot-starter-webflux:2.7.4` -> `spring-boot-starter-reactor-netty:2.7.4` -> `reactor-netty-http:1.0.23` -> `reactor-core:3.4.23`

So we need to use an earlier version of Spring starter instead of 2.7.4 (version 2.6.7 seems to be the most recent version which depends on an earlier version of `reactor-core:3.4.18`).
